backend = "glx";
vsync = true;
shadow = true;
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
animations = true;
animation-stiffness = 220;
animation-window-mass = 0.2;
animation-dampening = 25;
animation-for-open-window = "slide-up";
animation-for-unmap-window = "slide-down";

inactive-opacity = 0.9;
active-opacity = 1.0;
frame-opacity = 0.9;

blur-method = "dual_kawase";
blur-strength = 7;
blur-background = true;
blur-background-frame = true;
blur-kern = "7x7box";

