backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 30;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.5;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

animations = true;
animation-stiffness-in-tag = 125;
animation-stiffness-tag-change = 90;
animation-window-mass = 0.4;
animation-dampening = 15;
animation-clamping = true;

animation-for-open-window = "slide-up";
animation-for-unmap-window = "slide-down";
animation-for-transient-window = "slide-up";

animation-for-prev-tag = "minimize";
animation-for-next-tag = "slide-in-center";
enable-fading-prev-tag = true;
enable-fading-next-tag = true;

inactive-opacity = 0.9;
active-opacity = 1.0;
frame-opacity = 0.9;

corner-radius = 14;
rounded-corners-exclude = [
  "window_type = 'desktop'",
];

blur: {
  method = "dual_kawase";
  strength = 9;
  background = true;
  background-frame = false;
  background-fixed = false;
}

blur-background-exclude = [
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'Chromium'",
  "class_g = 'Discord'",
  "class_g = 'Dunst'",
  "class_g = 'Peek'",
  "class_g *?= 'slop'",
];

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { opacity = 1.0; shadow = true; blur = false; full-shadow = true; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 0.8; };
  dropdown_menu = { opacity = 0.8; };
};

